theme: jekyll-theme-slate
title: Ducretet L.024
description: A second vintage radio restaured.
show_downloads: true

github:
  zip_url:
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/